server:
  port: 9527

spring:
  datasource:
    dynamic:
      # 是否开启 SQL日志输出，生产环境建议关闭，有性能损耗
      p6spy: true
      hikari:
        connection-timeout: 30000
        max-lifetime: 1800000
        max-pool-size: 5
        min-idle: 5
        connection-test-query: select 1
        pool-name: JiebaoHikariCP
      # 配置默认数据源
      primary: primary
      datasource:
        # 数据源-1，名称为 primary
        primary:
          username: root #SYSDBA
#          password: link0122.. #jiebao@2008  jiebao@2008
#          password: 123456
          password: jiebao@2008
          driver-class-name:  com.mysql.cj.jdbc.Driver #dm.jdbc.driver.DmDriver
          #url: jdbc:dm://192.168.20.122:5236/SYSDBA?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
          #url: jdbc:dm://127.0.0.1:3306/SYSDBA?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
          url: jdbc:mysql://114.116.174.5:3306/pwp?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
#          url: jdbc:mysql://127.0.0.1:3306/pwp?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
        # 数据源-2，名称为 crm
        #crm:
        #  username: root
        #  password: jiebao@2008
        #  driver-class-name: com.mysql.cj.jdbc.Driver
        #  url: jdbc:mysql://114.116.174.5:3306/jiebao_shiro_crm?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  aop:
    proxy-target-class: true

  messages:
    encoding: utf-8

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  #文件上传大小限制
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB

  # Redis配置
  redis:
    host: 114.116.141.49
    port: 6379
    password: jiebaoredis
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 0
  resources:
    static-locations: file:D:\OA\img\

#mybatis plus 设置
mybatis-plus:
  type-aliases-package: com.jiebao.platfrom.system.domain,com.jiebao.platfrom.demo.domain,com.jiebao.platfrom.railway.domain
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    # 关闭 mybatis-plus的 banner
    banner: false

management:
  endpoints:
    web:
      exposure:
        include: ['httptrace', 'metrics']


jiebao:
#  host: http://114.115.147.159:9527
  host: http://127.0.0.1:9527
  #host: http://192.168.20.113:9527
  # 是否异步记录用户操作日志
  openAopLog: true
  # 单次最大批量入库数量
  max:
    batch:
      insert:
        num: 1000
  shiro:
    # 后端免认证接口 url
    anonUrl: /login,/logout/**,/regist,/user/check/**,/webjars/**,/swagger-resources/**,/swagger-ui.html#/,/swagger-ui.html,/v2/**,/jbx/cdn/image/**,/demo/**,/address/**,/mini/user/login/**,/mini/user/quickLogin/**
    # token有效期，单位秒
    jwtTimeOut: 600

  upload:
    #上传路径
    imagePath: /usr/local/rrpo/upload/images/ #D:/upload/images/
    filePath: /usr/local/rrpo/upload/files/  #D:/upload/files/

    #虚拟访问路径+
    staticImagePath: /jbx/cdn/image/**
    staticFilePath: /jbx/cdn/file/**

    #数据库存储虚拟路径
    image: /jbx/cdn/image/
    file: /jbx/cdn/file/

wx:
  miniapp:
    configs:
      - appid: wx67029b2a97acdda1
        secret: 6da3b18391c7eb57bae8cf3353c6a3d7
        msgDataFormat: JSON